### ISSUE TITLE
Yolov8 OBB

### ISSUE THREAD

**Issue by kevinzezel** [Qengineering/YoloV8-ncnn-Raspberry-Pi-4#11]
Hi,

Do you have an example of how to run post-processing for a yolov8 OBB model? 

Regards,
Kevin

**Comment by Qengineering** [comment]
What are you referring to with post-processing? 
Usually, post-processing is preparing the outcome to be human understandable. In other words, make nice images with bounding boxes.

**Comment by Qengineering** [comment]
I see.
Unfortunately, the current ncnn YoloV8 implementation doesn't support OBB.
As far as I know, there is no YoloV8-OBB for ncnn available (yet).
