### ISSUE TITLE
Yolov8 custom model (Segmentation Fault)

### ISSUE THREAD

**Issue by kevinzezel** [Qengineering/YoloV8-ncnn-Raspberry-Pi-4#12]
Hi,

I have a customized yolov8 model trained on my own dataset. How to convert to ncnn?

I tried to convert using onnx2ncnn, but I got this error:

```

./tools/onnx/onnx2ncnn model_custom.onnx

Shape not supported yet!
Unknown data type 0
Unknown data type 0
Unknown data type 0
```

I found it strange because there were no changes to the architecture in the yolov8 model.

Do you know what it could be?

Regards,
Kevin

**Comment by Qengineering** [comment]
Please follow [these instructions](https://portrait.gitee.com/FunXiaoYuZhou/YOLOv8-Custom-Object-Detection-Android).
