### ISSUE TITLE
Convert your own custom trained model to ncnn.

### ISSUE THREAD

**Issue by programmeddeath1** [Qengineering/YoloV8-ncnn-Raspberry-Pi-4#5]
How to convert your own custom ttrained yolov8 models to ncnn? What would be the process steps required to achieve this?
Thank you for your help in advance!

**Comment by Qengineering** [comment]
@programmeddeath1,

Please follow the steps at: https://github.com/FeiGeChuanShu/ncnn-android-yolov8
and https://github.com/FeiGeChuanShu/ncnn-android-yolov8/issues/8

**Comment by programmeddeath1** [comment]
Thank you! Do you also know if its possible to use NPU with ncnn and whether we can enable ncnn to use the rknn npu hardware for R3588 and other models?

**Comment by programmeddeath1** [comment]
> @programmeddeath1,
> 
> Please follow the steps at: https://github.com/FeiGeChuanShu/ncnn-android-yolov8 and [FeiGeChuanShu/ncnn-android-yolov8#8](https://github.com/FeiGeChuanShu/ncnn-android-yolov8/issues/8)


I converted my model and tried to run using the same code it fails with segmentation fault at output extraction
"""
find_blob_index_by_name output failed
Try
    ex.extract("output0", out0);
Segmentation fault
"""

**Comment by Qengineering** [comment]
@programmeddeath1,

About your first question; no, unfortunately, ncnn does not support any NPU. In fact there not one popular framework supporting the RK3588. You have to use the [RKNPU](https://github.com/rockchip-linux/rknpu2) framework and the supporting [Toolkit](https://github.com/rockchip-linux/rknn-toolkit2)

About your porting issue. I'm not in the position to debug your model, nor do I have any time. Please use [Netron](https://netron.app/) to see topology of your model and its output naming. For a distance, it looks a naming issue.

**Comment by programmeddeath1** [comment]
Hi thank you for your response and guidance! I will debug it and see it in detail, I will just need some help to point me in the right direction as I'm new to this domain application. I will check the topology and output format and try once.
